RANK_TO_TYPE = {
    1: 'A',
    2: '2',
    3: '3',
    4: '4',
    5: '5',
    6: '6',
    7: '7',
    8: '8',
    9: '9',
    10: '10',
    11: 'J',
    12: 'Q',
    13: 'K',
}

FULL_DECK = {
    'A-H': {'suit': 'hearts', 'count': 1, 'rank': 1,},
    '2-H': {'suit': 'hearts', 'count': 2, 'rank': 2,},
    '3-H': {'suit': 'hearts', 'count': 3, 'rank': 3,},
    '4-H': {'suit': 'hearts', 'count': 4, 'rank': 4,},
    '5-H': {'suit': 'hearts', 'count': 5, 'rank': 5,},
    '6-H': {'suit': 'hearts', 'count': 6, 'rank': 6,},
    '7-H': {'suit': 'hearts', 'count': 7, 'rank': 7,},
    '8-H': {'suit': 'hearts', 'count': 8, 'rank': 8,},
    '9-H': {'suit': 'hearts', 'count': 9, 'rank': 9,},
    '10-H': {'suit': 'hearts', 'count': 10, 'rank': 10,},
    'J-H': {'suit': 'hearts', 'count': 10, 'rank': 11,},
    'Q-H': {'suit': 'hearts', 'count': 10, 'rank': 12,},
    'K-H': {'suit': 'hearts', 'count': 10, 'rank': 13,},
    'A-D': {'suit': 'diamonds', 'count': 1, 'rank': 1,},
    '2-D': {'suit': 'diamonds', 'count': 2, 'rank': 2,},
    '3-D': {'suit': 'diamonds', 'count': 3, 'rank': 3,},
    '4-D': {'suit': 'diamonds', 'count': 4, 'rank': 4,},
    '5-D': {'suit': 'diamonds', 'count': 5, 'rank': 5,},
    '6-D': {'suit': 'diamonds', 'count': 6, 'rank': 6,},
    '7-D': {'suit': 'diamonds', 'count': 7, 'rank': 7,},
    '8-D': {'suit': 'diamonds', 'count': 8, 'rank': 8,},
    '9-D': {'suit': 'diamonds', 'count': 9, 'rank': 9,},
    '10-D': {'suit': 'diamonds', 'count': 10, 'rank': 10,},
    'J-D': {'suit': 'diamonds', 'count': 10, 'rank': 11,},
    'Q-D': {'suit': 'diamonds', 'count': 10, 'rank': 12,},
    'K-D': {'suit': 'diamonds', 'count': 10, 'rank': 13,},
    'A-C': {'suit': 'clubs', 'count': 1, 'rank': 1,},
    '2-C': {'suit': 'clubs', 'count': 2, 'rank': 2,},
    '3-C': {'suit': 'clubs', 'count': 3, 'rank': 3,},
    '4-C': {'suit': 'clubs', 'count': 4, 'rank': 4,},
    '5-C': {'suit': 'clubs', 'count': 5, 'rank': 5,},
    '6-C': {'suit': 'clubs', 'count': 6, 'rank': 6,},
    '7-C': {'suit': 'clubs', 'count': 7, 'rank': 7,},
    '8-C': {'suit': 'clubs', 'count': 8, 'rank': 8,},
    '9-C': {'suit': 'clubs', 'count': 9, 'rank': 9,},
    '10-C': {'suit': 'clubs', 'count': 10, 'rank': 10,},
    'J-C': {'suit': 'clubs', 'count': 10, 'rank': 11,},
    'Q-C': {'suit': 'clubs', 'count': 10, 'rank': 12,},
    'K-C': {'suit': 'clubs', 'count': 10, 'rank': 13,},
    'A-S': {'suit': 'spades', 'count': 1, 'rank': 1,},
    '2-S': {'suit': 'spades', 'count': 2, 'rank': 2,},
    '3-S': {'suit': 'spades', 'count': 3, 'rank': 3,},
    '4-S': {'suit': 'spades', 'count': 4, 'rank': 4,},
    '5-S': {'suit': 'spades', 'count': 5, 'rank': 5,},
    '6-S': {'suit': 'spades', 'count': 6, 'rank': 6,},
    '7-S': {'suit': 'spades', 'count': 7, 'rank': 7,},
    '8-S': {'suit': 'spades', 'count': 8, 'rank': 8,},
    '9-S': {'suit': 'spades', 'count': 9, 'rank': 9,},
    '10-S': {'suit': 'spades', 'count': 10, 'rank': 10,},
    'J-S': {'suit': 'spades', 'count': 10, 'rank': 11,},
    'Q-S': {'suit': 'spades', 'count': 10, 'rank': 12,},
    'K-S': {'suit': 'spades', 'count': 10, 'rank': 13,},
}
